version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   db

    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"

    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        links:
            - db
        ports:
            - "8183:8080"
